event_inherited();
sprite_hit = spr_plant_hit;
mask_index = sprite_index;
count_shoot = 0;
max_count_shoot = 3;
is_shoot = false;
dir = image_xscale;
shoot_range = 600;
shoot_timer = 120;
max_shoot_timer = 120;
name = "plant";