event_inherited();
sprite_hit = spr_trunk_hit;
is_shoot = false;
dir = image_xscale;
shoot_range = 1000;
shoot_timer = 30;
max_shoot_timer = shoot_timer;
move_spd = 3;
move_x = 0;
dir = choose(1, -1);
wait_time = 90;
name = "trunk";